name: Publish to GitHub Packages

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
      checks: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish library package
        run: ./gradlew :AppstentComposeLibray:assembleRelease :AppstentComposeLibray:publish --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          
      - name: Wait for package to be available
        run: sleep 30
        
      - name: List published packages
        run: |
          echo "Checking for published package..."
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/orgs/Appversation/packages/maven/com.appversation.appstent-compose/versions
          echo "\nVerifying if version 1.6.3 is available..."

      - name: Build app
        run: ./gradlew :app:build --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
